using System.Collections.ObjectModel;
// This file is prgrammatically generated by ConvertToVsTemplate based on scanning the input template files
namespace WL12ModuleItem.CppTemplates.WL12ModuleTemplate
{
     public class CompositeSymbols {
         public static readonly ReadOnlyCollection<string> conditionArray = new ReadOnlyCollection<string>(new string[] {
        "!MULTI_MODE&&PTS_COLUMN",
        "!NO_DXCC||!NO_NAMEDMULT||!NO_ZONE||!NO_AYGMULT",
        "!NO_DXCC||!NO_ZONE",
        "!NO_DXCC||!NO_ZONE||!NO_AYGMULT||!NO_NAMEDMULT",
        "!NO_DXCC||!NO_ZONE||!NO_NAMEDMULT||!NO_AYGMULT",
        "!NO_NAMEDMULT&&!NO_AYGMULT",
        "!NO_NAMEDMULT||!NO_AYGMULT",
        "!NO_NAMEDMULT||!NO_DXCC||!NO_ZONE||!NO_AYGMULT",
        "CABRILLO&&MULTIPLE_NAMED_IN_QSO",
        "MULTIPLE_NAMED_IN_QSO&&!NO_NAMEDMULT",
        "MULTI_MODE&&!NO_NAMEDMULT",
        });
    }
}
